### ISSUE TITLE
Sperren der Projektplanungsfelder bei der Projekterstellung

### ISSUE THREAD

**Issue by lukcod3** [Agent77326/Zuteilungsalgorithmus#10]
Im Lehrer-Interface müssen die Projektplanungsfelder gesperrt werden an denen überhaupt kein Projekt mehr stattfindet.

**Comment by Yasamato** [comment]
Was meinst du genau? Kannst du dass bitte noch etwas ausführen?

**Comment by lukcod3** [comment]
Momentan kann/muss man als Lehrer an jedem Wochentag, egal ob der Admin eingestellt hat, dass an diesem Tag bzw. Vor- oder Nachmittag überhaupt Projektwoche ist, einen Tagesablauf eintragen. Die Felder müssen also abhängig von der config teilweise deaktiviert werden.

**Comment by Yasamato** [comment]
Sollte mit dem [Commit ](https://github.com/Agent77326/Zuteilungsalgorithmus/commit/7571bc1e3c726ce8a07e3aaca9b94cd67843eaa3) hinzugefügt worden sein.
