### ISSUE TITLE
Erstellen eines PDFs aller Projekte

### ISSUE THREAD

**Issue by lukcod3** [Agent77326/Zuteilungsalgorithmus#11]
Im Dashboard soll man eine Möglichkeit haben ein PDF zu erstellen in dem alle Projekte schön formatiert und druckbereit  aufgelistet sind.

**Comment by Yasamato** [comment]
Könnten ja über den media-query `@media print` in css die Druckvorlage gestalten.

**Comment by Zykai** [comment]
Dafür müsste man aber die Projekte in Dashboard anzeigen können. Ich kann mir eher vorstellen das in Java umzusetzen, bin mir aber nicht sicher ob das dann gut aussieht.

**Comment by Zykai** [comment]
Für Java gibt es die Library [PDFBox von Apache](https://pdfbox.apache.org/). Ich wollte ein PDF-Dokument mit Forms erstellen und die Textfelder mit der Library ausfüllen. Sollte auch möglich sein. Sie stürzt bei mir aber immer ab (nicht wegen dem Code).
![vorlage](https://user-images.githubusercontent.com/35534281/37875498-bc535090-3040-11e8-90b4-1f07d12806bf.jpg)

Mit [jsPDF](https://github.com/MrRio/jsPDF) kann man PDFs auf der Client-Seite erstellen. Man kann die Dateien per Hand erstellen oder HTML in die Datei einfügen. Per Hand wäre es sehr aufwendig und für in HTML einfügen brauchen wir ne Übersicht der Projekte.

Die Java-Lösung gefällt mir mehr und es sollte auch leichter sein, sie umzusetzen. Man muss die Lib halt nur zum laufen bringen.

**Comment by Yasamato** [comment]
Du musst ja nicht die PDFs an sich erstellen, sondern nur eine Druckvorlage.

**Comment by Yasamato** [comment]
Könnten aber genau so gut einfach auf dem server eine jar laufen lassen, die das dann generiert.

**Comment by Zykai** [comment]
Habe einen [Pull-Request](https://github.com/Agent77326/Zuteilungsalgorithmus/pull/22) erstellt. Man kann jetzt eine einfache Übersicht der Projekte als pdf erstellen

**Comment by Yasamato** [comment]
Wollen wir das noch fertig machen? Wäre nützlich für jedes Projekt einzeln eine PDF erstellen zu können sowie eine Gesamtübersicht der Projekte mit den grundlegenden Infos und jeweils die PDFs für die Teilnehmerlisten der Projekte damit man die einfach aushängen kann.

**Comment by Yasamato** [comment]
Ich hab mich mal an deine Vorlage gehalten und eine native css sowie html-Lösung zum Drucken implementiert

> Für Java gibt es die Library [PDFBox von Apache](https://pdfbox.apache.org/). Ich wollte ein PDF-Dokument mit Forms erstellen und die Textfelder mit der Library ausfüllen. Sollte auch möglich sein. Sie stürzt bei mir aber immer ab (nicht wegen dem Code).
> ![vorlage](https://user-images.githubusercontent.com/35534281/37875498-bc535090-3040-11e8-90b4-1f07d12806bf.jpg)
> 
> Mit [jsPDF](https://github.com/MrRio/jsPDF) kann man PDFs auf der Client-Seite erstellen. Man kann die Dateien per Hand erstellen oder HTML in die Datei einfügen. Per Hand wäre es sehr aufwendig und für in HTML einfügen brauchen wir ne Übersicht der Projekte.
> 
> Die Java-Lösung gefällt mir mehr und es sollte auch leichter sein, sie umzusetzen. Man muss die Lib halt nur zum laufen bringen.
