### ISSUE TITLE
Dashboard non scrollable

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#18]
Bei einer Bildschirmbreite von <= 575px, kommt es schon zu dem Fehler, dass der obere Teil nach Oben verschwindet, und auch nicht durch scrollen wieder eingeblendet werden kann. Getestet in Firefox und Chrome

**Comment by lukcod3** [comment]
Sollte mit dem Comit #21 behoben sein.
