### ISSUE TITLE
Wahl immer noch nicht touch-fähig

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#20]
Naja...

**Comment by Zykai** [comment]
Das hängt aber an dem Browser vom Handy/Tablet

**Comment by Yasamato** [comment]
Nicht nur, Touch-Berührungen haben separate Events.

**Comment by Yasamato** [comment]
Sollte mit Pull #24 gefixt worden sein

**Comment by Yasamato** [comment]
Wobei Safari immer noch nicht der touch funktioniert.

**Comment by Yasamato** [comment]
Wir sollten wahrscheinlich lieber alles auf eine externe js-lib umstellen anstatt nativ selbst das zu implementieren um vollen Support auf den modernen Platformen zu bekommen.

Ich hätte eine js-Lib gefunden namens [interact](http://interactjs.io/). Bei der Libary wird auch Multi-Touch etc unterstützt und funktioniert sogar in IE9...

**Comment by Yasamato** [comment]
Mit #39 behoben, jedoch treten neue Probleme auf.

**Comment by Yasamato** [comment]
Wieder irgendwie verbuggt, schau mir das später mal an.

**Comment by Yasamato** [comment]
see https://github.com/taye/interact.js/issues/709
