### ISSUE TITLE
dashboard form submit

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#3]
Beim dashboard sind die inputs zur konfiguration nicht veränderbar, sowie der nicht funktionierende form submit.

**Comment by tintinmaster** [comment]
Die Datei die ich noch habe, ist in dem Zustand bevor sie auf den campus server rüber gezogen wurde und demenstprechend angepasst wurde. Da ist irgendetwas schief gelaufen, denn die Datei so funktioniert prima mit den checkboxes und dem submit. Das Laden klappt aber nicht

**Comment by Yasamato** [comment]
Lad sie mal in deinen Branch hoch und schick den Link. Ich schau dann mal, ob ich das fixen kann.

**Comment by lukcod3** [comment]
Eigentlich sollte alles bis auf das Laden der letzten Spalte, also ob am ersten Vormittag noch Unterricht ist, funktionieren. Außerdem haben Tim und Ich die form eigentlich schöner gestaltet, das CSS wird aber irgendwie nicht geladen.

**Comment by Yasamato** [comment]
dashboard.js missing

**Comment by Yasamato** [comment]
die html datei ist nämlich identisch (abgesehen davon, dass ich sie in 2 Teile geteilt hab: form-handler und html-handler)

**Comment by Yasamato** [comment]
Sollte mit meinem Pull gefixt sein. Schaut auf meinen Test-Server nach, ob es auch wirklich funktioniert.
