### ISSUE TITLE
Drucken der Schülerlisten mit den Wahlen

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#35]
Noch nicht implementiert. Wie soll das gestaltet werden? Oder mit der Liste des Wahlergebnisses kombinieren, sodass pro Zeile in der Tabelle nicht nur der Schüler samt seinen Wahlen steht, sondern auch noch das Wahlergebnis am Schluss. Oder sollte man das lieber in zwei seperate Tabellen aufteilen? Die Tabelle nach Klasse und Stufe sortieren und dann jeweils eine eigene Druckseite? oder nach Namen und Wahlergebnis? Oder alles davon?

**Comment by Zykai** [comment]
Brauchen wir das überhaupt? Anstelle die Wahl zu drücken bräuchte man eher etwas, um das Ergebnis zu drucken.

**Comment by Yasamato** [comment]
Ja, dann bieten wir einfach eine Druckvorlage für das Ergebnis an als Tabellen, welche nach Jahrgang und Klasse sortiert sind mit den Daten: Name, Vorname, Wahlen, Wahlergebnis
