### ISSUE TITLE
Dashboard über beta.agent nicht erreichbar

### ISSUE THREAD

**Issue by tintinmaster** [Agent77326/Zuteilungsalgorithmus#4]
Es wird eine leere Seite angezeigt
<body> ist leer !!

**Comment by tintinmaster** [comment]
Warum haben wir eigentlich einmal html/dashboard.PHP und eimal php/dashboard.php ???
Meiner Meinung nach war die ganze Zeit dashboard.php die richtige und lag am selben Ort wie die index.php und war ne html, aber mit php tags deswegen .php und die dashboard.PHP im html war veraltet und konnte nicht gelöscht werden, da nur du berechtigungen hattest und du dich gerade nicht anmelden konntest.. Oder liege ich da falsch ?

**Comment by Yasamato** [comment]
mb hatte die Datei umbenannt und vergessen in index.php zu ändern.

Das eine unter php/ ist für das handhaben vom formular zuständig, während das andere nur mit der Darstellung vom Dashboard zuständig wäre.
