### ISSUE TITLE
Admin Page Bug

### ISSUE THREAD

**Issue by tintinmaster** [Agent77326/Zuteilungsalgorithmus#43]
Beim erstmaligen Laden des Admin Dashboards ist die Projektanzahl 0, erst beim refreshen der Seite wird die richtige Projektanzahl angezeigt

**Comment by Yasamato** [comment]
Fixed mit #45 bzw. dem [Commit](https://github.com/Agent77326/Zuteilungsalgorithmus/pull/45/commits/bae8e4d42ab667fa6401702d8d8f524802b59123)
