### ISSUE TITLE
Verbesserung Design Admin Page

### ISSUE THREAD

**Issue by tintinmaster** [Agent77326/Zuteilungsalgorithmus#44]
Einheitliche Farbe der Box ohne Trennlinie

**Comment by tintinmaster** [comment]
![](https://i.imgur.com/rCUqDxt.png)

**Comment by Yasamato** [comment]
Du meinst einfach den Hintergrund komplett die Farbe?

**Comment by Yasamato** [comment]
Das wäre mein Vorschlag.
![image](https://user-images.githubusercontent.com/27964795/54228358-4c11d900-4502-11e9-90e1-0905a4a80dcd.png)

**Comment by Yasamato** [comment]
Hab die Trennlinie noch raus gemacht

**Comment by tintinmaster** [comment]
Das halt in der in meinem Bild Orange umrandeten Fläche alles eine Farbe ist und nicht so eine dunklere Linie und so so ein bisschen dunkler Fläche

**Comment by Yasamato** [comment]
So?
![image](https://user-images.githubusercontent.com/27964795/54229053-c858ec00-4503-11e9-9484-41b2e472dbba.png)

**Comment by tintinmaster** [comment]
Ich weiß jetzt nicht wo das ist aber um das zu fixen muss folgendes gemacht werden.
In CSS
`card-footer` darf keine `border-top` haben 
Und `background-color` muss #343a40 sein

**Comment by tintinmaster** [comment]
Wow, da war ich zu langsam. Ja das meine ich

**Comment by Yasamato** [comment]
Ich setz noch auf die bg-color

> Ich weiß jetzt nicht wo das ist aber um das zu fixen muss folgendes gemacht werden.
> In CSS
> `card-footer` darf keine `border-top` haben
> Und `background-color` muss #343a40 sein

**Comment by Yasamato** [comment]
Ah das war bereits der Standard-Wert... nevermind

**Comment by tintinmaster** [comment]
Geht das noch dass alle Karten eine Höhe haben?

**Comment by tintinmaster** [comment]
Das das halt mehr wie ein Grid aussieht wie oben rechts

**Comment by Yasamato** [comment]
Ich denke das entspricht dem was du meinst oder?
![image](https://user-images.githubusercontent.com/27964795/54233723-d449ab80-450d-11e9-86b7-427cd92ed34f.png)

**Comment by tintinmaster** [comment]
Das sieht gut aus. So hab ich mir das vorgestellt
