### ISSUE TITLE
Handling beim Löschen eines Projektes bei bereits getätigten Wahlen

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#46]
Wie sollte man damit umgehen?
Was wenn sich dadurch die Zahl der benötigten Wahlfelder ändert?

**Comment by JanPfenning** [comment]
Neuwahlen von denen die dieses Projekt gewählt haben denke ich.

**Comment by Yasamato** [comment]
done
