### ISSUE TITLE
Manual anfertigen

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#47]
Wir sollten eine Bedienungsanleitung anfertigen damit selbst unerfahrene Leute unser Projekt einsetzen können.

**Comment by Yasamato** [comment]
Oder in Form eines Wiki hier auf Github

**Comment by tintinmaster** [comment]
Zur Bedienung oder wie man das einbindet und/oder Sachen am Code ändert?

**Comment by JanPfenning** [comment]
Ich fände ein PDF schöner, wenn das keiner tun will mach ich das gerne.

**Comment by XizTenS** [comment]
Ich fände ein PDF schöner, wenn das keiner tun will mach ich das gerne.

**Comment by Yasamato** [comment]
Kann man ja konvertieren. Hier die Wiki können wir halt gemeinsam jederzeit bearbeiten. Am Ende können wir dann ja eine Bedienungsanleitung.pdf anfertigen oder so.
