### ISSUE TITLE
Scipt Blocker Warnung

### ISSUE THREAD

**Issue by tintinmaster** [Agent77326/Zuteilungsalgorithmus#49]
Wenn man einen Script Blocker aktiviert hat (So wie es sich für einen Schüler aus Herr Müllers Lehre gehört), funktionieren viele Aktionen nicht.
Ist es möglich dies zu erkennen und darauf hinzuweisen oder lassen wir das einfach so und man muss selbst darauf kommen seinen Script Blocker zu deaktivieren?

**Comment by Yasamato** [comment]
Mit was hast du das ausprobiert? Komplett Javascript deaktiviert? Weil wenn ein Script Blocker drauf ist kann man nichts mehr machen da kein Script ausgeführt werden könnte um das sofort zu testen

**Comment by tintinmaster** [comment]
Mit uMatrix, da werden erstmal externe Scripts geblockt 
![image](https://user-images.githubusercontent.com/36089973/54719293-c7a40380-4b5c-11e9-9798-05c5cd747889.png)

**Comment by Yasamato** [comment]
ja gut... mach eine lokale Kopie von allen libs und schau dann noch mal
