### ISSUE TITLE
Anpassung der Verteilung an AG-Wahlen

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#5]
Für die AG-Wahlen müsste noch der Verteilungs-Algorithmus sowie die Projekt(AG)-Erstellung angepasst werden samt Datenstrukturen im Hintergrund.

Möglich wäre auch dies über das Dashboard zu steuern und so dies einzustellen.

**Comment by tintinmaster** [comment]
Ich würde das für AG's extra machen. z.B brauch hier nicht jeder Lehrer dieses Formular, da die AG's meistens eh die selben sind und nur ab und zu neue hinzukommen oder entfernt werden. Ich würde erstmal das hier fertig machen, das alles läuft und es dann kopieren und anpassen

**Comment by fabianvdW** [comment]
Ich würde auch das ganze kopieren und dann seperat dran arbeiten
