### ISSUE TITLE
Verschiebung von Button

### ISSUE THREAD

**Issue by tintinmaster** [Agent77326/Zuteilungsalgorithmus#50]
Wäre es nicht sinnvoller den Button „Einstellung“ auf der Admin Seite in das Konfigurations-Pop-Up zu verschieben und die Beschriftung in „Klassendatensätze änder“ zu ändern. 

Ebenso sinnvoll wäre es anstelle dieses Buttons ein „Auflisten” Button zu platzieren um aufzulisten, welche Klassen vollständig gewählt haben und welche nicht.

**Comment by Yasamato** [comment]
Hab die Beschriftung in „Klassendatensätze ändern“ geändert vom Button. Macht das Auflisten Sinn? Ist ja unterhalb alles da. Könnte einen Anker hin machen

**Comment by Yasamato** [comment]
@tintinmaster ?

**Comment by Yasamato** [comment]
https://github.com/Agent77326/Zuteilungsalgorithmus/commit/01895504ade38fd15b7b2790eba8c38806accf37
