### ISSUE TITLE
Beispieldatensätze anlegen

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#53]
Wir **sollten** mal wirklich sinnvolle Beispielwahlen mit Projekten anfertigen, welche wir präsentieren können.

Dringend wir das erst in ein paar Wochen benötigt. Davor lösche ich alle Daten erst mal und geb dann per WhatsApp oder so Bescheid.

**Comment by JanPfenning** [comment]
Ich kann die wahlen nicht simulieren weil meine wahlen immer in <klassenstufe>test eingetragen werden und nicht in <klassenstufe><klasse>
