### ISSUE TITLE
Datenstruktur von den Schulservern verifizieren

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#57]
Müsste man verifizieren für die Zwangszuteilung und Dokumentation.

**Comment by Yasamato** [comment]
Ebenso müsste man noch mal nachfragen wie das Home-Verzeichnis (aus welchem wir die Klasse auslesen) aufgebaut ist bei der Oberstufe.

**Comment by JanPfenning** [comment]
4nachname+3vorname ist die u id wenn du das meinst
Also pfenjan oder jungleo

**Comment by Yasamato** [comment]
- [x] U-ID
Ist die U-ID, welche wir erhatlen tatsächlich der Login-Name?
- [x] Klasse/Stufe
Momentan extahieren wir das bei unserem live-login durch das Home-Verzeichnis. Wie war noch mal die Ordner-Struktur?
Login-Skript [hier](https://github.com/Agent77326/Zuteilungsalgorithmus/blob/9791d3faeb11d3cf9689787551611d0b906747cc/web/php/login_live.php#L42).

**Comment by JanPfenning** [comment]
Das müssen wir mit einem Informatiker aus der Schule zusammen machen denke
ich.

Agent77326 <notifications@github.com> schrieb am Di., 26. März 2019, 21:12:

**Comment by JanPfenning** [comment]
Kannst du da nicht einfach gruenbeck oder Müller ne Mail schicken?

**Comment by lukcod3** [comment]
Die momentan für die Authentifizierungsserver  eingetragene IP "10.16.1.1" ist nicht online. Wir sollten nach nem Hostname oder einer neuen IP fragen.

**Comment by Yasamato** [comment]
Also: Unter- und Mittelstufe wie gehabt, (kein Problem). Nur ab der 10. gibt es keine Klassen mehr, da sind alle im Topf 10er, 11er bzw. 12er.
