### ISSUE TITLE
Schüler Wahl am handy

### ISSUE THREAD

**Issue by JanPfenning** [Agent77326/Zuteilungsalgorithmus#59]
Oberstes linkes Projekt kann aktuell nicht an 4. Stelle gezogen werden, weil beim scrollen die Seite mit dem Projekten nicht sticky ist

**Comment by Yasamato** [comment]
Das Projekte sind sticky-top, jedoch "stoßen" sie unten am ende von html auf den Bildschirmrand und werden so nach oben geschoben. Um das zu lösen müssten wir uns einen besseren Designansatz ausdenken oder einen Hack anwenden.

**Comment by JanPfenning** [comment]
Dann lass es lieber so haha :D

Agent77326 <notifications@github.com> schrieb am Di., 26. März 2019, 21:04:

**Comment by Yasamato** [comment]
Fürs erste.

**Comment by Yasamato** [comment]
Hab mal die Spacings von dem Wahl-Card angepasst. Passt das besser?

**Comment by JanPfenning** [comment]
Ja viel schöner so fürs Handy.
Unter dem letzten Eintrag würde ich den freien Platz noch kleiner machen
damit die ganze Liste rechts drauf passt wenn 4 Projekte drin sind. Am PC
kann man die denke ich auch ein kleines bisschen kleiner machen wenn ich
mich richtig erinnere aber da sage ich später nochmal bescheid.

Agent77326 <notifications@github.com> schrieb am Mi., 27. März 2019, 11:36:
