### ISSUE TITLE
Warnung bei wenig überschüssigen Plätzen

### ISSUE THREAD

**Issue by JanPfenning** [Agent77326/Zuteilungsalgorithmus#61]
Wenn weniger als 105% Freie Plätze für 100% Schüler vorhanden sind sollte es eine Warnung geben (bei 900 schülern sollten es 945 Plätze geben um zwangszuweisung zu vermeiden)

**Comment by Yasamato** [comment]
Was sollten wir dann als Wert nehmen? 5%? 10%?

**Comment by JanPfenning** [comment]
5% sind sinnvoll denke ich. 10% sind zu viel

Agent77326 <notifications@github.com> schrieb am Di., 26. März 2019, 20:35:

**Comment by JanPfenning** [comment]
Ich würde es nicht als Fehler sondern als Warnung machen. Wenn weniger
Plätze als Schüler da sind dann ist es ein Fehler. So würde ich es gelb
lassen

Agent77326 <notifications@github.com> schrieb am Di., 26. März 2019, 20:52:

**Comment by JanPfenning** [comment]
Sehr schön jetzt..würde es aber trotzdem gelb machen wenn theoretisch genug Plätze da sind nur halt nicht viele im Überschuss. Rot würde ich es nur machen wenn wirklich weniger Plätze als Schüler vorhanden sind
