### ISSUE TITLE
QUESTION Zwangszuteilung

### ISSUE THREAD

**Issue by JanPfenning** [Agent77326/Zuteilungsalgorithmus#63]
Wenn ein Schüler vor der Zuteilung durch den Algorithmus durch den Admin zwangszugeteilt wird, wird er dann in dem Algorithmus zur verteilung noch beachtet? er sollte gar nicht in den Algorithmus eingeschläust werden und das Projekt dem er Zwangszugeteilt wurde sollte beim wert "maximale schüler anzahl" -1 bekommen, da er ja bereits in diesem Projekt fest drin ist

**Comment by Yasamato** [comment]
Ja so hatten wir das auch vor. Die Teilnehmergrenzen (min und max) werden jeweils -1 gerechnet
