### ISSUE TITLE
Klasse erfordert zusätzlich Klassenstufe -> redundanz

### ISSUE THREAD

**Issue by JanPfenning** [Agent77326/Zuteilungsalgorithmus#64]
![image](https://user-images.githubusercontent.com/27968404/55026361-1d682800-5003-11e9-8e7e-85db19d2641c.png)

Es ist sehr unangenehm beim Eintragen in der Klasse noch ein weiteres mal die Stufe anzugeben und in meinen augen auch sehr unnötig. am besten einfach nur die Klasse angeben also:
a
b
c
oder in der OS:
Ch1
M1
Bio1

**Comment by Yasamato** [comment]
Wegen in #57 genannten Problem der Datenstruktur von den Klassen/Stufe bin ich mir nicht sicher ob wir das einfach machen können. Würde lieber das vorher kontrollen bevor ich da Arbeit reinstecke.

**Comment by JanPfenning** [comment]
Okay keine eile. Man kann es denke ich dann so machen dass die Klasse die
man Einträge nur der buchstabe oder Stammkurs bezeichnung ist aber die
Klasse in der Datenstruktur wird zusammengesetzt aus dem Stufen string und
dem string im input also der Klasse.
Interface:
Stufe 5
Klasse a
->Datenstruktur:
Stufe 5
Klasse 5a

Agent77326 <notifications@github.com> schrieb am Di., 26. März 2019, 21:13:
