### ISSUE TITLE
Handywahl Projekt oben links nicht auf platz 4

### ISSUE THREAD

**Issue by JanPfenning** [Agent77326/Zuteilungsalgorithmus#66]
Man kann das projekt oben links nicht auf den 4. platz setzen, weil die liste rechts zu lang ist. man sollte beim scrollen die projekte links so lange oben haben bis die wahlliste rechts am 4. punkt angekommen ist 
(schwer zu erklären probiert es mal aus)

**Comment by Yasamato** [comment]
#59 duplicated
