### ISSUE TITLE
Anzeigefehler im Dashboard bei Zwangzuteilungen

### ISSUE THREAD

**Issue by lukcod3** [Agent77326/Zuteilungsalgorithmus#69]
Wenn das Modal zur Projektzwangszuteilung eines Schülers durch den Button 'Ändern' mehrfach geöffnet und geschloßen wird, wird bei jedem neuen Öffnen jedes Projekt neu zu dieser Liste hinzugefügt, was zu Dopplungen führt in der Liste führt.

**Comment by Yasamato** [comment]
Fixed.
