### ISSUE TITLE
Keine Wahl getätigt -> Wildcards bei der Zuteilung

### ISSUE THREAD

**Issue by Yasamato** [Agent77326/Zuteilungsalgorithmus#83]
Nach Abschluss der Wahlphase sollten alle fehlenden Schüler per Hand vom Admin eingetragen werden, welche irgendeinem Projekt zugeteilt werden, sodass dieses beispielsweise stattfindet oder einfach nur leere Plätze auffüllt.

Hierzu müsste im Admin-Dashboard ein Formular eingefügt werden ähnlich der Zwangszuteilung, sowie der Algorithmus angepasst werden.

**Comment by fabianvdW** [comment]
Hatten wir uns nicht darauf geeinigt, dass diese Schüler zunächst ignoriert werden (damit sie keine Projektplätze von beliebten Projekten wegnehmen) und dann anschließend zwangszugeteilt werden?

**Comment by Yasamato** [comment]
Ja, aber dass diese anschließend vom Algorithmus zwangszugeteilt werden müssen und dadurch ja evtl. Projekte ermöglicht werden, welche vorher nicht möglich waren bzw. mehr ihre höhere Wahl bekommen.
